version: '3.8'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: webshop
    ports:
      - "5432:5432"
  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:12345@db/webshop
    ports:
      - "8000:8000"
    volumes:
      - .:/app